name: enpal_assessment_project
version: '1.0.0'

profile: enpal_assessment_project

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["raw_data"] # Updated the path
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  enpal_assessment_project:
    # Config indicated by + and applies to all files under models/example/
    +schema: pipedrive_analytics
    +materialized: table

seeds:
  enpal_assessment_project:
    fields:
      column_types:
        id: integer
        field_key: text
        name: text
        field_value_options: jsonb